# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Путівник ДВНЗ "УжНУ"
description: > # this means to ignore newlines until "baseurl:"
  Ресурс призначений для абітурієнтів УжНУ, щоб допомогти ознайомитися із структурою університету.

baseurl: "" # the subpath of your site, e.g. /blog
url: "www.uzhnu.edu.ua/uk/" 
E-mail: email
comision: "Адреса: 88000, Україна, Закарпатська обл., м. Ужгород, вул. Університетська, 14, кімн. 228 Телефон: +38 (0312) 64-30-84, 066-5716240, 096-123-89-67 E-mail: admission@uzhnu.edu.ua"


footer-names:
github_username:  "GitHub Pages" 
jekyll_username: Jekyll

footer-links:
you-tube_link: "https://www.youtube.com/channel/UCSIfo-iRoeS7nf5957HnI0Q/videos"
github_link:  "https://pages.github.com/"
facebook_link: "https://facebook.com/uzhnu/"
vk_link: "http://vk.com/uzhhorodnationaluniversity"
jekyll_link: "https://jekyllrb.com/"

image: 

# Build settings
markdown: kramdown
